#![allow(dead_code)]

mod ex_25_break_random_access_readwrite_aes_ctr;
mod ex_26_ctr_bitflipping;
mod ex_27_recover_key_from_cbc;
mod ex_28_sha1_keyed_mac;
mod ex_29_break_sha1_keyed_mac_length_extension;
mod ex_30_break_md4_keyed_mac_length_extension;
mod ex_31_implement_and_break_hmac_sha1_with_an_artificial_timing_leak;
